package org.abos.twi.gatcha.core.effect;

public enum EffectType {

    DAMAGE_BLUNT,
    DAMAGE_SLASH,
    DAMAGE_PIERCE,
    DAMAGE_ARMOR_PIERCE,
    DAMAGE_DEATH,
    DAMAGE_SOUND,
    DAMAGE_FROST,
    BUFF_ATTACK,
    BUFF_DEFENSE,
    BUFF_SPEED,
    BUFF_HEALTH,
    DEBUFF_SPEED,
    RESIST_DEATH,
    LOWER_ACCURACY,
    BLEED,
    HEALING,
    INVISIBILITY,
    INVULNERABILITY,
    STUN,
    DISPEL,
    ANNOY,
    SUMMON,
    TURN_FRIENDLY

}
